### ISSUE TITLE
[feature-request] Add customizability to tolerance info of custom substances

### ISSUE THREAD

**Issue by Weemizo** [isaakhanimann/psychonautwiki-journal-ios#10]
Make custom substances dynamic enough to give user more capabilities such as:

- custom tolerance info
- duration
[and maybe]
- interactions
- dosage info

**Comment by Lygre** [comment]
Any suggestions on how you'd like to see tolerance information input? Beyond mild, moderate, high?

**Comment by Weemizo** [comment]
adding just time of tolerance to custom substances, e.g. fasoracetam has 7-14 days tolerance, I would set it as 14 days, instead of having "Missing tolerance info for x"

**Comment by Weemizo** [comment]
Didnt know, but some substances aren't on PW. Just asking - is anybody able to edit information on PW similarly to wikipedia

**Comment by jms74** [comment]
But PW lacks a lot of substances, just look at altnoids, it doesn't even
have one and they are among one the most used substances nowadays.

e-mail me @ ***@***.***

have a nice day / night

A segunda, 3/06/2024, 08:01, Isaak ***@***.***> escreveu:

**Comment by isaakhanimann** [comment]
What are altnoids?
I often hear people from the community complaining that the community isn't adding info on substances. Do it yourself

**Comment by jms74** [comment]
Alternative natural cannabinoids.

e-mail me @ ***@***.***

have a nice day / night

A segunda, 3/06/2024, 10:54, Isaak ***@***.***> escreveu:

**Comment by jms74** [comment]
If there was a simple way to add I bet a lot of people would add, just look
at other services..
The thing is wiki editing isn't for the "lot of people", it's not easy to
get into for most, there's no intelligent editor that shows possible
mistakes and such.
Even if you go thru that then there's the next phase that's getting your
editing approved. Been and seen users complaining about no approval after .
If you do one or twice and then there's no approval you start to think why
I'm I doing this?

Wiki editing is selecting as it's not from reach of most users. Yeah they
could learn but everyone could also learn how to create a rocket..



e-mail me @ ***@***.***

have a nice day / night

A segunda, 3/06/2024, 12:15, Isaak ***@***.***> escreveu:

**Comment by isaakhanimann** [comment]
I know what you mean. Its just too much work to do this in the app and then it would not even be available to anyone else. If there was a better, more complete source of info than PW I would use that but I'm not aware of one and I don't have the time and money to build and manage one.
In any case editing the article to update dosage and duration info is doable. Approval process is also necessary because people might die if info is inaccurate.
