### ISSUE TITLE
[Feature-request] More Language Support?

### ISSUE THREAD

**Issue by shilapi** [isaakhanimann/psychonautwiki-journal-ios#11]
I have used the app for days and it's generally great for me.
Just want to kindly request for multi language support.
I can help doing translation to Chinese.

**Comment by isaakhanimann** [comment]
This would mean translating all the wiki and all of the texts in the app and preparing the whole app for translation. And whenever I would work on the app and add something new I would need to consult someone to translate. This is not feasible for such a small project.
