### ISSUE TITLE
[feature request] Confidence interval instead of standard deviation

### ISSUE THREAD

**Issue by RomanHauksson** [isaakhanimann/psychonautwiki-journal-ios#16]
I'm grateful to be able to specify when I have uncertainty about the size of a dose, but I don't have good intuition for translating my feeling of uncertainty into a standard deviation. Instead, I'd like to specify a dose range with a percentage confidence – for example, "I'm 80% confident my cup of coffee had between 50 and 130 miligrams of caffeine". This could then be translated into parameters for a given probability distribution.

**Comment by isaakhanimann** [comment]
I don't think its mathematically possible to convert your statement into a probability distribution. However I could convert the standard deviation definition into multiple statements like yours that are easier to understand.
E.g.
10 +- 2 becomes "68% confidence that its 8-12" or "95% confidence that its 6-14"

**Comment by isaakhanimann** [comment]
I just added this

**Comment by RomanHauksson** [comment]
Thanks so much!
