### ISSUE TITLE
Traveling though time zones makes the graphs look strange

### ISSUE THREAD

**Issue by f2k1de** [isaakhanimann/psychonautwiki-journal-ios#7]
When traveling across different time zones, the continuous experience graph becomes distorted and displays incorrectly shaped progressions.

Also, in my case, the Live activity widget stopped working the moment the time zone changed and everything added later was no longer taken into account.

**Comment by isaakhanimann** [comment]
Probably was a reloading issue where you were just in the experience screen and it didnt get reloaded when you switched timezones. However its correct if you navigate back and then forth again.
