### ISSUE TITLE
Tapentadol duration graph missing

### ISSUE THREAD

**Issue by Baftastic** [isaakhanimann/psychonautwiki-journal-ios#9]
Image: 
![image](https://github.com/isaakhanimann/psychonautwiki-journal-ios/assets/94781687/5bba904e-aae3-469b-acaa-092f97132920)

**Comment by Baftastic** [comment]
I never seen this bug on any other substances btw

**Comment by isaakhanimann** [comment]
As you can see only the onset and peak are defined. So the comeup and offset are missing which are required for the app to draw the full timeline. You can add these durations in PsychonautWiki and then it will also be available in the next app release.
